# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_entry.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flog_entry.proto\x12\rlogprocessing\"\xe8\x01\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x37\n\x08metadata\x18\x05 \x03(\x0b\x32%.logprocessing.LogEntry.MetadataEntry\x12\x12\n\nrequest_id\x18\x06 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x07 \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"_\n\x08LogBatch\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.logprocessing.LogEntry\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61tch_timestamp\x18\x03 \x01(\x03\"\xa2\x01\n\x12PerformanceMetrics\x12\x1c\n\x14serialization_format\x18\x01 \x01(\t\x12\x1d\n\x15serialization_time_ms\x18\x02 \x01(\x01\x12\x1f\n\x17\x64\x65serialization_time_ms\x18\x03 \x01(\x01\x12\x17\n\x0f\x64\x61ta_size_bytes\x18\x04 \x01(\x03\x12\x15\n\rentries_count\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_entry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY_METADATAENTRY']._options = None
  _globals['_LOGENTRY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=35
  _globals['_LOGENTRY']._serialized_end=267
  _globals['_LOGENTRY_METADATAENTRY']._serialized_start=220
  _globals['_LOGENTRY_METADATAENTRY']._serialized_end=267
  _globals['_LOGBATCH']._serialized_start=269
  _globals['_LOGBATCH']._serialized_end=364
  _globals['_PERFORMANCEMETRICS']._serialized_start=367
  _globals['_PERFORMANCEMETRICS']._serialized_end=529
# @@protoc_insertion_point(module_scope)
