FROM python:3.10-slim

WORKDIR /app

COPY src /app/src
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install flask

# Create a volume mount point for logs
VOLUME ["/app/logs"]

# Expose the UDP port and dashboard port
EXPOSE 9999/udp
EXPOSE 8080

CMD ["python", "-m", "src.server.udp_server"]