FROM python:3.10-slim

WORKDIR /app

COPY src /app/src
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "src.client.udp_client", "--server", "udp-server", "--count", "10000"]