FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./
RUN npm install

# Copy source
COPY frontend/src ./src
COPY frontend/public ./public

EXPOSE 3000

CMD ["npm", "start"]
